### ISSUE TITLE
Menubar toggle is not working in mobile view

### ISSUE THREAD

**Issue by dhavalsavalia** [pythonindia/inpycon2018#133]
Menubar toggle is not working in mobile view.

Here are screenshots:

![screen shot 2018-06-13 at 6 57 04 pm](https://user-images.githubusercontent.com/27001046/41354054-a3e693de-6f3b-11e8-999c-b55471f48b04.png)

**Comment by realslimshanky** [comment]
@dhavalsavalia I can see you have pushed a commit in your forked repo which contains the fix. Please create a PR for review.

**Comment by dhavalsavalia** [comment]
@realslimshanky The issue has already been fixed by another contributor. See, Ananyo's comment on my PR https://github.com/pythonindia/inpycon2018/pull/134#issuecomment-397315329

**Comment by bhansa** [comment]
We should close this issue, if it's already fixed by someone.

**Comment by ananyo2012** [comment]
This isn't fixed yet. This was caused due to missing js files which is pending in #134. You changed the navbar links which wasn't required in the PR. That was what I mentioned.

**Comment by ananyo2012** [comment]
Fixed in #134
